
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eos.exampel.org
  resources:
  - eosclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eos.exampel.org
  resources:
  - eosclusters/status
  verbs:
  - get
  - patch
  - update
